version: 1.0.{build}
image: Visual Studio 2019
environment:
  APPVEYOR_RDP_PASSWORD: un1sh@Windows114514
  
build_script:
  - cmd: echo "test build..."
test: off

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
